/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Archivo;
import java.io.FileNotFoundException;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class frmResgistodoctor extends javax.swing.JFrame {

    /**
     * Creates new form frmLoing
     */
    public frmResgistodoctor() {
        initComponents();
        this.setLocationRelativeTo(null);
        buttonGroup2.add(rbtActivo);
        buttonGroup2.add(rbtInactivo);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        strNameD = new javax.swing.JLabel();
        txtNameD = new javax.swing.JTextField();
        strNumeroC = new javax.swing.JLabel();
        txtNumeroC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        strEstado = new javax.swing.JLabel();
        rbtActivo = new javax.swing.JRadioButton();
        rbtInactivo = new javax.swing.JRadioButton();
        btlimpiar = new javax.swing.JButton();
        btEntrar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        cmbEspedialidad = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        strNameD.setFont(new java.awt.Font("OCR A Std", 0, 13)); // NOI18N
        strNameD.setText("Nombre:");

        txtNameD.setFont(new java.awt.Font("OCR A Std", 0, 13)); // NOI18N
        txtNameD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameDActionPerformed(evt);
            }
        });
        txtNameD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameDKeyTyped(evt);
            }
        });

        strNumeroC.setFont(new java.awt.Font("OCR A Std", 0, 13)); // NOI18N
        strNumeroC.setText("Numero Consultorio:");

        txtNumeroC.setToolTipText("");
        txtNumeroC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroCKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("OCR A Std", 0, 13)); // NOI18N
        jLabel2.setText("Especialidad:");

        strEstado.setFont(new java.awt.Font("OCR A Std", 0, 13)); // NOI18N
        strEstado.setText("Estado");

        rbtActivo.setText("Activo");

        rbtInactivo.setText("Inactivo");

        btlimpiar.setFont(new java.awt.Font("OCR A Std", 0, 13)); // NOI18N
        btlimpiar.setText("Limpiar");
        btlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlimpiarActionPerformed(evt);
            }
        });

        btEntrar.setFont(new java.awt.Font("OCR A Std", 0, 13)); // NOI18N
        btEntrar.setText("Enviar");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 0));
        jTextField1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("REGISTRAR DOCTORES");

        cmbEspedialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Medico General", "Pediatra", "Cirujano", "Dentista", "Optapmólogo" }));
        cmbEspedialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbEspedialidadMouseClicked(evt);
            }
        });
        cmbEspedialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEspedialidadActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("OCR A Std", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/x-mark-hi.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("OCR A Std", 0, 13)); // NOI18N
        jLabel1.setText("Apellidos:");

        txtApellido.setFont(new java.awt.Font("OCR A Std", 0, 13)); // NOI18N
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(txtNumeroC, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(cmbEspedialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2)
                                .addComponent(strEstado)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rbtActivo)
                                    .addGap(32, 32, 32)
                                    .addComponent(rbtInactivo)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(strNameD)
                                .addComponent(strNumeroC)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNameD, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                        .addComponent(txtApellido)))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btlimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btEntrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(strNameD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNameD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(strNumeroC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbEspedialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(strEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtActivo)
                    .addComponent(rbtInactivo))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btlimpiar)
                    .addComponent(btEntrar))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Método Limpiar">  
    public void limpiar() {
        txtNameD.setText("");
        txtNumeroC.setText("");
        txtApellido.setText("");
        cmbEspedialidad.setSelectedItem("");

    }// </editor-fold> 

    // <editor-fold defaultstate="collapsed" desc="Estado">  
    private String Estado() {
        String Estado = "";
        if (rbtActivo.isSelected()) {
            Estado = "Activo";
        }
        if (rbtInactivo.isSelected()) {
            Estado = "Inactivo";
        }
        return Estado;
    }// </editor-fold> 
    
    // <editor-fold defaultstate="collapsed" desc="Validar y Guardar los datos">  
    public void Validar() {
        Archivo objArchivo = new Archivo();

        int intName = txtNameD.getText().length();
        int intNumeroC = txtNumeroC.getText().length();
        int intApellido= txtApellido.getText().length();
        int intrbtActivo = rbtActivo.getText().length();
        int intrbtInactivo = rbtActivo.getText().length();
        
        if ((intName == 0) || (intNumeroC == 0)|| (intrbtActivo == 0)|| (intrbtInactivo == 0)|| (intApellido == 0)) {
            JOptionPane.showMessageDialog(null, "ERROR, NO ESTAN LLENOS TODO LOS REQUISITOS");
        }else{
            objArchivo.AgregarRegistroDoctor(txtNameD.getText(), txtApellido.getText(), txtNumeroC.getText(), (String) cmbEspedialidad.getSelectedItem(),Estado());
            JOptionPane.showMessageDialog(null, "DATOS CORRECTAMENTE GUARDADOS");
            limpiar();
        }
    } // </editor-fold> 

    // <editor-fold defaultstate="collapsed" desc="Control entrada">  
    // </editor-fold>

    private void txtNameDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameDActionPerformed

    private void btlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btlimpiarActionPerformed

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        Validar();
      
    }//GEN-LAST:event_btEntrarActionPerformed

    private void txtNameDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameDKeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            evt.consume();

            JOptionPane.showMessageDialog(null, "En este campo solo se perimte texto");

            txtNameD.setCursor(null);
        }
    }//GEN-LAST:event_txtNameDKeyTyped

    private void txtNumeroCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroCKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();

            JOptionPane.showMessageDialog(null, "En este campo solo se perimte variables enteras");

            txtNumeroC.setCursor(null);
        }
    }//GEN-LAST:event_txtNumeroCKeyTyped

    private void cmbEspedialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEspedialidadActionPerformed
        
    }//GEN-LAST:event_cmbEspedialidadActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbEspedialidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbEspedialidadMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbEspedialidadMouseClicked

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();

            JOptionPane.showMessageDialog(null, "En este campo solo se perimte texto");

            txtApellido.setCursor(null);
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntrar;
    private javax.swing.JButton btlimpiar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbEspedialidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rbtActivo;
    private javax.swing.JRadioButton rbtInactivo;
    private javax.swing.JLabel strEstado;
    private javax.swing.JLabel strNameD;
    private javax.swing.JLabel strNumeroC;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNameD;
    private javax.swing.JTextField txtNumeroC;
    // End of variables declaration//GEN-END:variables
}
