/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class JfrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form JfrmLoginn
     */
    public JfrmLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbInformation = new javax.swing.JLabel();
        jbtEntrar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbInformation.setFont(new java.awt.Font("Nanum Brush Script", 0, 12)); // NOI18N
        jlbInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/information-icon-29.png"))); // NOI18N
        jlbInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbInformationMouseClicked(evt);
            }
        });
        getContentPane().add(jlbInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jbtEntrar.setBackground(new java.awt.Color(153, 153, 153));
        jbtEntrar.setFont(new java.awt.Font("Nanum Brush Script", 0, 20)); // NOI18N
        jbtEntrar.setText("Entrar");
        jbtEntrar.setToolTipText("");
        jbtEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtEntrarMouseClicked(evt);
            }
        });
        jbtEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        jbtCancelar.setBackground(new java.awt.Color(153, 153, 153));
        jbtCancelar.setFont(new java.awt.Font("Nanum Brush Script", 0, 20)); // NOI18N
        jbtCancelar.setText("Cancelar");
        jbtCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtCancelarMouseClicked(evt);
            }
        });
        getContentPane().add(jbtCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        txtPassword.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 180, 130, -1));

        jLabel3.setFont(new java.awt.Font("Nanum Brush Script", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Passoword:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 30));

        jLabel2.setFont(new java.awt.Font("Nanum Pen Script", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        txtNickname.setFont(new java.awt.Font("Nanum Gothic", 0, 14)); // NOI18N
        getContentPane().add(txtNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 140, -1));

        jLabel1.setFont(new java.awt.Font("Nanum Pen Script", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema centro Medico \"San Diego\"");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo-de-medicina-para-descarga-gratuita_23-2147490182.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 440, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtEntrarMouseClicked
        // TODO add your handling code here:
        String Usuario = "admin";
        String Password = "admin123";

        if (txtNickname.getText().equals(Usuario) && txtPassword.getText().equals(Password)) {
            JfrmDesktop desktop = null;
            try {
                desktop = new JfrmDesktop();
            } catch (PropertyVetoException ex) {
                Logger.getLogger(JfrmLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            desktop.setVisible(true);
            dispose();

        } else {
            JOptionPane.showMessageDialog(this, "El usuario o contranseña es incorrecta");
        }
    }//GEN-LAST:event_jbtEntrarMouseClicked

    private void jbtCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtCancelarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jbtCancelarMouseClicked

    private void jlbInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbInformationMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Este sistema fue creado por @DiegoPinto\n con la finalidad de parctica para fin de ciclo de cuarto UTPL");
    }//GEN-LAST:event_jlbInformationMouseClicked

    private void jbtEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEntrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtEntrar;
    private javax.swing.JLabel jlbInformation;
    private javax.swing.JTextField txtNickname;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
